### ISSUE TITLE
2343: Bug: New Reservation: Pax count incorrect for WL rooms

### ISSUE THREAD

**Issue by farhorizonindia** [farhorizonindia/FH.RR#4]
Pax count issue is there in waitlisted bookings. This needs to be sorted out urgently as this is hampering our work.
![pax](https://cloud.githubusercontent.com/assets/24309056/21072072/639bef38-bedc-11e6-99d8-8cd5e696e69e.JPG)

**Comment by farhorizonindia** [comment]
Booking not working 20160812003227 and 20161203003426

**Comment by farhorizonindia** [comment]
Screenshot attached

![room count issue](https://cloud.githubusercontent.com/assets/24309056/21295178/4e053e96-c575-11e6-90cb-832fa3c0e843.PNG)
![room count issue2](https://cloud.githubusercontent.com/assets/24309056/21295177/4df6ccda-c575-11e6-8d4f-ddcd2e4e0a56.PNG)

**Comment by farhorizonindia** [comment]
As discussed the steps to recreate the issue is:
Step1: Edit an existing booking
Step2: Change the no of cabins from the drop down, Here the no of pax does not get updated even if there are rooms available.

**Comment by farhorizonindia** [comment]
We made a test booking on Cruise for 15-22 Jan 2017 with 4, 1, 4 cabins. It was giving an issue sometimes.
Booking id 20161223003524, you may want to edit the no of cabins on this booking and see.

**Comment by amit-ros** [comment]
This issue is fixed and deployed in the test folder.

Kindly Test

**Comment by farhorizonindia** [comment]
Amit, this seems to be working on the live instance. The test instance has not got activated yet unfortunately. I will check by evening.

**Comment by farhorizonindia** [comment]
Amit the application on the link http://test.adventureresortscruises.in/ did not seem so to work. So I am unable to test. I have asked mitsu to look into the issue. Will revert by tomorrow if they happen to resolve the issue tomorrow, else Monday 26 Dec 2016.

**Comment by farhorizonindia** [comment]
Amit, finally the test application is working. You need to click on http://test.adventureresortscruises.in/Default.aspx to open the application. It is not opening by just entering http://test.adventureresortscruises.in.

We did test this issue on the booking no 20161226003527 15-22 Jan 2017 booking on cruise and the problem still persists. You can see the issue on this booking. If you make the count of rooms from 4 to 9 it happens, from 9 to 1 it happens but then when you select 2 or 3 it becomes 4.
